# Generated by Django 6.0 on 2025-12-04 09:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[("Home", "Home"), ("Work", "Work"), ("Fun", "Fun")],
                        default="Work",
                        max_length=4,
                    ),
                ),
                ("important", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TrackModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
