# Generated by Django 6.0 on 2025-12-05 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 12, 5, 7, 47, 41, 74130)
            ),
        ),
    ]
