# Generated by Django 6.0 on 2025-12-05 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_taskmodel_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 12, 5, 8, 45, 50, 346870)
            ),
        ),
    ]
