# Generated by Django 6.0 on 2025-12-05 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_taskmodel_done_alter_taskmodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 5, 8, 47, 23, 698180, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
